# base image
FROM node:16-alpine3.14

# integrating working directory of node image
WORKDIR /app

# caching the dependencies to working directory(WRKDIR) of container
COPY package.json .
# COPY ./package-lock.json ./
# installing dependecies
RUN npm install
# copying the folders from root to working directory(WRKDIR) of container
COPY . .

# exposing the port

# starting react server in container 
CMD ["npm","run", "start"]

# port-mapping
# docker run -p 8080:8080 <docker id/docker name>
